substitutions:
  hostname: "camaracueva"
  ssid: !secret wifi_ssid
  password: !secret wifi_password
esphome:
  name: $hostname
  platform: ESP32
  board: esp32dev
wifi:
  ssid: $ssid
  password: $password
  fast_connect: True
api:
  encryption:
    key: "bGNXLeoM9aSZ3gI8G/4XKNw6Om/lmwtsoeT5oZ8UBVU="
  reboot_timeout: 0s
ota:
  - platform: esphome
    password: "1306e3ce804b3d70a31ac63f23e9724c"
logger:

# ESP32-CAM - OJO que estas opciones varian según el modelo
esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  name: CamaraCueva

# Luz/flash de la camara
output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4

# Entidad (interruptor) para Home Assistant (opcional)   
light:
  - platform: binary
    output: gpio_4
    name: Luz camara
