esphome:
  name: esp01
  platform: ESP8266
  board: nodemcu

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "*****"

ota:
  - platform: esphome
    password: "*****"
    
web_server:
  port: 80
  
sensor:
  - platform: dht
    pin: 2
    temperature:
      name: "Temperatura Cocina"
    humidity:
      name: "Humedad Cocina"
    update_interval: 30s
